# Copyright (c) 2023 Bitcoin Association Distributed under the Open BSV
# software license, see the accompanying file LICENSE

name: 'Autotools unit test'
description:  'Autotools Unit test'
runs:
  using: "composite"
  steps:
    - run: make -j$(nproc --all) VERBOSE=1 check
      shell: bash
